FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD winnova.jar /opt/winnova/
EXPOSE 8080
WORKDIR /opt/winnova/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "winnova.jar"]
